version: "3.9"
services:
  vpn-wsl2-proxy:
    build:
      context: .
    environment: 
      - PROXY_HOST=your_company_proxy_host # change it to your company proxy.
      - PROXY_PORT=8080 # change it to your proxy port.
    restart: always
    ports: 
      - "3128:3128"
